language: perl
perl:
   - "5.22"
   - "5.20"
   - "5.18"
   - "5.16"

services:
   - postgresql

before_script:
   - psql -c 'CREATE DATABASE delta_reporting_test;' -U postgres
   - psql -c 'CREATE USER deltar_ro;' -U postgres
   - psql -c 'CREATE USER deltar_rw;' -U postgres
   - psql -c 'GRANT SELECT ON ALL TABLES IN SCHEMA public TO deltar_ro;' -U postgres
   - psql -c 'GRANT ALL ON ALL TABLES IN SCHEMA public TO deltar_rw;' -U postgres

install:
   - cpanm -n Test::More Net::DNS Regexp::Common Sys::Hostname::Long DBI DBD::Pg IO::Socket::IP Log::Log4perl
   - echo 'perl [$PERL]'
   - echo 'which perl:'; which perl
   - echo 'perl version:'; perl -v

script:
   - cd app; perl DeltaR.pl test

sudo: false

notifications:
   email: false
